# Generated by Django 2.2.5 on 2019-09-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peertotur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('paddress', models.CharField(max_length=200)),
                ('pemail', models.CharField(max_length=100)),
                ('pmajor', models.CharField(max_length=100)),
                ('pdep', models.CharField(max_length=100)),
                ('pgpamajor', models.CharField(max_length=10)),
                ('pgpacum', models.CharField(max_length=100)),
                ('pexgraduate', models.IntegerField(max_length=4)),
                ('reqdate', models.DateTimeField(auto_now=True)),
                ('ptel', models.CharField(max_length=20)),
                ('pgsm', models.CharField(max_length=20)),
                ('yearofstudy', models.CharField(choices=[('Soph', 'Sopph'), ('Jr', 'Jr'), ('Sr', 'Sr'), ('Grad_Student', 'Grad_Student')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Peertoturq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortq', models.TextField()),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peertotur.Peertotur')),
            ],
        ),
        migrations.CreateModel(
            name='Peertoturfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=500)),
                ('filepath', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peertotur.Peertotur')),
            ],
        ),
        migrations.CreateModel(
            name='Peertoturexperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
                ('coursecode', models.CharField(max_length=10)),
                ('fp', models.BooleanField(default=False)),
                ('un', models.BooleanField(default=False)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peertotur.Peertotur')),
            ],
        ),
    ]
