# Generated by Django 2.2.5 on 2019-09-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peertotur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200, verbose_name='Name')),
                ('paddress', models.CharField(max_length=200, verbose_name='Address')),
                ('pemail', models.CharField(max_length=100, verbose_name='E-mail address')),
                ('pmajor', models.CharField(max_length=100, verbose_name='Major')),
                ('pdep', models.CharField(max_length=100, verbose_name='Department')),
                ('pgpamajor', models.CharField(max_length=10, verbose_name='GPA in major')),
                ('pgpacum', models.CharField(max_length=100, verbose_name='Cumulative GPA')),
                ('pexgraduate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Expected date of Graduation')),
                ('reqdate', models.DateTimeField(auto_now_add=True)),
                ('ptel', models.CharField(max_length=20, verbose_name='Tel')),
                ('pgsm', models.CharField(max_length=20, verbose_name='GSM')),
                ('yearofstudy', models.CharField(choices=[('Soph', 'Sopph'), ('Jr', 'Jr'), ('Sr', 'Sr'), ('Grad_Student', 'Grad_Student')], max_length=20, verbose_name='Year of Study')),
                ('pimg', models.ImageField(blank=True, null=True, upload_to='peertoturs/img/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Peertoturfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=500)),
                ('filepath', models.FileField(blank=True, null=True, upload_to='peertoturs/uploads/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='StudentComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('mbody', models.CharField(blank=True, max_length=300, null=True)),
                ('mstatus', models.BooleanField(default=False)),
                ('mdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peertoturq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortq', models.TextField()),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peertotur.Peertotur')),
            ],
        ),
        migrations.CreateModel(
            name='Peertoturexperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
                ('coursecode', models.CharField(max_length=10)),
                ('fp', models.BooleanField(default=False)),
                ('un', models.BooleanField(default=False)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peertotur.Peertotur')),
            ],
        ),
    ]
