# Generated by Django 2.2.5 on 2019-09-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ftitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='file title'),
        ),
    ]
