# Generated by Django 2.2.5 on 2019-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0002_auto_20190918_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peertotur',
            name='reqdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
