# Generated by Django 2.2.5 on 2019-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0002_document_ftitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='peertoturq',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='peertoturq',
            name='shortq',
            field=models.TextField(blank=True, null=True, verbose_name='Answer'),
        ),
    ]
