# Generated by Django 2.2.5 on 2019-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0003_remove_peertoturfile_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='peertotur',
            name='pimg',
            field=models.ImageField(blank=True, null=True, upload_to='peertoturs/img/'),
        ),
    ]
