# Generated by Django 2.2.5 on 2019-09-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0003_auto_20190919_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peertotur',
            options={'ordering': ['-reqdate']},
        ),
    ]
