# Generated by Django 2.2.5 on 2019-09-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0003_auto_20190927_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peertoturq',
            name='question',
        ),
        migrations.RemoveField(
            model_name='peertoturq',
            name='shortq',
        ),
        migrations.AddField(
            model_name='peertoturq',
            name='answer1',
            field=models.TextField(blank=True, null=True, verbose_name='Answer1'),
        ),
        migrations.AddField(
            model_name='peertoturq',
            name='answer2',
            field=models.TextField(blank=True, null=True, verbose_name='Answer2'),
        ),
        migrations.AddField(
            model_name='peertoturq',
            name='answer3',
            field=models.TextField(blank=True, null=True, verbose_name='Answer3'),
        ),
        migrations.AddField(
            model_name='peertoturq',
            name='question1',
            field=models.TextField(blank=True, null=True, verbose_name='Question1'),
        ),
        migrations.AddField(
            model_name='peertoturq',
            name='question2',
            field=models.TextField(blank=True, null=True, verbose_name='Question2'),
        ),
        migrations.AddField(
            model_name='peertoturq',
            name='question3',
            field=models.TextField(blank=True, null=True, verbose_name='Question3'),
        ),
    ]
