# Generated by Django 2.2.5 on 2019-09-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0004_peertotur_pimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peertotur',
            name='paddress',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='pdep',
            field=models.CharField(max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='pemail',
            field=models.CharField(max_length=100, verbose_name='E-mail address'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='pexgraduate',
            field=models.CharField(max_length=12, verbose_name='Expected date of Graduation'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='pgpacum',
            field=models.CharField(max_length=100, verbose_name='Cumulative GPA'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='pgpamajor',
            field=models.CharField(max_length=10, verbose_name='GPA in major'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='pgsm',
            field=models.CharField(max_length=20, verbose_name='GSM'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='pimg',
            field=models.ImageField(blank=True, null=True, upload_to='peertoturs/img/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='pmajor',
            field=models.CharField(max_length=100, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='pname',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='ptel',
            field=models.CharField(max_length=20, verbose_name='Tel'),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='reqdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='peertotur',
            name='yearofstudy',
            field=models.CharField(choices=[('Soph', 'Sopph'), ('Jr', 'Jr'), ('Sr', 'Sr'), ('Grad_Student', 'Grad_Student')], max_length=20, verbose_name='Year of Study'),
        ),
    ]
