# Generated by Django 2.2.5 on 2019-09-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0004_auto_20190927_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peertoturq',
            name='question1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Question1'),
        ),
        migrations.AlterField(
            model_name='peertoturq',
            name='question2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Question2'),
        ),
        migrations.AlterField(
            model_name='peertoturq',
            name='question3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Question3'),
        ),
    ]
