# Generated by Django 2.2.5 on 2019-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0005_auto_20190920_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peertoturexperties',
            options={'ordering': ['coursename']},
        ),
        migrations.AlterField(
            model_name='peertoturexperties',
            name='coursecode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='peertoturexperties',
            name='coursename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='peertoturexperties',
            name='fp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='peertoturexperties',
            name='un',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
