# Generated by Django 2.2.5 on 2019-09-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0006_auto_20190920_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peertoturexperties',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peertotur.Peertotur', verbose_name='Peer Totur List'),
        ),
    ]
