# Generated by Django 2.2.5 on 2019-09-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0007_auto_20190920_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peertoturexperties',
            name='un',
        ),
    ]
