# Generated by Django 2.2.5 on 2019-09-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0008_remove_peertoturexperties_un'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='peertoturs/mydocs/', verbose_name='Document')),
            ],
        ),
    ]
