# Generated by Django 2.2.5 on 2019-09-28 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('datein', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 28, 17, 46, 8, 107993), null=True, verbose_name='Time In')),
                ('dateout', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 28, 17, 46, 8, 108017), null=True, verbose_name='Time Out')),
            ],
            options={
                'ordering': ['-datein'],
            },
        ),
    ]
