# Generated by Django 2.2.5 on 2019-09-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerreg',
            name='dateout',
        ),
        migrations.AddField(
            model_name='peerreg',
            name='timein',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Time In'),
        ),
        migrations.AddField(
            model_name='peerreg',
            name='timeout',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Time Out'),
        ),
        migrations.AlterField(
            model_name='peerreg',
            name='datein',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Date In'),
        ),
        migrations.AlterField(
            model_name='peerreg',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peertotur.Peertotur', verbose_name='Peer Totur List'),
        ),
    ]
